---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list: ["recipe[kafka::default]"]
  attributes: {}
- name: binary
  run_list: ["recipe[kafka::binary]"]
  attributes: {}
