---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
    ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    attributes:
      java:
        jdk_version: 7
  - name: debian-7.4
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7
  - name: fedora-20
    attributes:
      java:
        jdk_version: 7

suites:
  - name: init-style-upstart
    run_list:
      - recipe[java::default]
      - recipe[kafka::default]
    excludes:
      - centos-6.5
      - debian-7.4
      - fedora-20
    attributes:
      kafka:
        init_style: 'upstart'
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        broker:
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000
  - name: init-style-sysv
    run_list:
      - recipe[java::default]
      - recipe[kafka::default]
    attributes:
      kafka:
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        broker:
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000
  - name: source-init-style-upstart
    run_list:
      - recipe[java::default]
      - recipe[kafka::default]
    excludes:
      - centos-6.5
      - debian-7.4
      - fedora-20
    attributes:
      kafka:
        install_method: 'source'
        init_style: 'upstart'
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        broker:
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000
  - name: source-init-style-sysv
    run_list:
      - recipe[java::default]
      - recipe[kafka::default]
    attributes:
      kafka:
        install_method: 'source'
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        broker:
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000
