name             'kafka'
maintainer       'Sous-Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs and configures a Kafka broker'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '3.0.0'
chef_version     '>= 13.0'
source_url       'https://github.com/mthssdrbrg/kafka-cookbook'
issues_url       'https://github.com/mthssdrbrg/kafka-cookbook/issues'

supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'debian'
supports 'ubuntu'
