source 'https://rubygems.org'

group :test do
  gem 'rake'
  gem 'stove'
  gem 'foodcritic', '< 5'
  gem 'berkshelf', '< 4'
  gem 'chef', '= 11.6.2'
  gem 'rspec', '= 2.14.1'
  gem 'chefspec', '= 3.4.0'
end
